[FIX] 'requirements.txt' added
andrewk10/AutoCompliance pull request #21
Opened 2022-03-07 09:29 UTC by 0x30c4

Added requirements.txt to the project.
Nothing else.

2022-03-07 20:51 UTC, andrewk10 requested changes
`client.set_missing_host_key_policy(AutoAddPolicy())` should be changed to `client.set_missing_host_key_policy(RejectPolicy)` in lines 105, 189 and 365 of net_propagation.py as per the codeql security scan fail seen here; [Link](https://codeql.github.com/codeql-query-help/python/py-paramiko-missing-host-key-validation/). This wasn't your fault but mine, I'm just making a note of it here since it reared it's ugly head in your pull request. ;) If you don't want to make that change it's fine I'll include it in the work I'm doing at the moment just let me know. :) I'm very happy with the requirements.txt addition and the main.py changes but I will ask you to set the branch you merge into as sprint 3 instead of the main branch please. Thanks a million for contributing!

2022-03-08 14:13 UTC, 0x30c4 commented
@andrewk10 done. let me know how was it

2022-03-08 17:57 UTC, andrewk10 approved these changes

2022-03-08 17:57 UTC, andrewk10 commented
> @andrewk10 done. let me know how was it

Perfect, thanks a million, turns out I could change the base branch myself anyway. :)

2022-03-08 17:58 UTC, merged